// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7hK0ngjXlOehUTmvMjz4XdvMwTRocXbA',
    appId: '1:329775269910:web:0bab3ce10f09d6334a4d37',
    messagingSenderId: '329775269910',
    projectId: 'ecolens-e0ecd',
    authDomain: 'ecolens-e0ecd.firebaseapp.com',
    storageBucket: 'ecolens-e0ecd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO2cjGV5P_nhDa40Zs04fxe3iA5RIDums',
    appId: '1:329775269910:ios:b0d9415065f86a934a4d37',
    messagingSenderId: '329775269910',
    projectId: 'ecolens-e0ecd',
    storageBucket: 'ecolens-e0ecd.firebasestorage.app',
    iosBundleId: 'com.example.ecolens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO2cjGV5P_nhDa40Zs04fxe3iA5RIDums',
    appId: '1:329775269910:ios:b0d9415065f86a934a4d37',
    messagingSenderId: '329775269910',
    projectId: 'ecolens-e0ecd',
    storageBucket: 'ecolens-e0ecd.firebasestorage.app',
    iosBundleId: 'com.example.ecolens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7hK0ngjXlOehUTmvMjz4XdvMwTRocXbA',
    appId: '1:329775269910:web:503dd29eb849d0c14a4d37',
    messagingSenderId: '329775269910',
    projectId: 'ecolens-e0ecd',
    authDomain: 'ecolens-e0ecd.firebaseapp.com',
    storageBucket: 'ecolens-e0ecd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5yIfTYKEFUp5OlYuQOCi28FpVfaQa03Y',
    appId: '1:329775269910:android:14e9fc0c5ded6b6a4a4d37',
    messagingSenderId: '329775269910',
    projectId: 'ecolens-e0ecd',
    storageBucket: 'ecolens-e0ecd.firebasestorage.app',
  );
}
